FROM ubuntu:14.04

RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install nodejs
RUN apt-get -y install npm
COPY ./App /src
RUN cd /src; npm install
EXPOSE 8080
CMD ["nodejs", "/src/main.js", "8080"]