#!/bin/bash

docker pull localhost:5000/main-app:latest
docker stop app-blue
docker rm app-blue
docker rmi localhost:5000/main-app:current
docker tag localhost:5000/main-app:latest localhost:5000/main-app:current
docker run -p 3002:8080 -d --name app-green localhost:5000/main-app:latest
